### ISSUE TITLE
OOB Failure - Example Does not Execute

### ISSUE THREAD

**Issue by thygrrr** [neurosity/neurosity-python-sdk#7]
I'm facing multiple issues with example.py / the "SDK":

Basically it appears as if the library is dependent on a very specific set of requirements, which is not reflected correctly in requirements.txt.

In a Python 3.10 venv on Windows 11 Pro x64, trying to run the example will yield the following output:

`C:\Projects\neurosity-python-sdk\venv\Scripts\python.exe C:\Projects\neurosity-python-sdk\examples\example.py 
Traceback (most recent call last):
  File "C:\Projects\neurosity-python-sdk\examples\example.py", line 7, in <module>
    neurosity = NeurositySDK({
  File "C:\Projects\neurosity-python-sdk\neurosity\neurosity.py", line 27, in __init__
    signal.signal(signal.SIGHUP, self.exit_handler)
AttributeError: module 'signal' has no attribute 'SIGHUP'
Exception ignored in atexit callback: <bound method NeurositySDK.exit_handler of <neurosity.neurosity.NeurositySDK object at 0x0000020CBA085B70>>
Traceback (most recent call last):
  File "C:\Projects\neurosity-python-sdk\neurosity\neurosity.py", line 30, in exit_handler
    self.remove_client()
  File "C:\Projects\neurosity-python-sdk\neurosity\neurosity.py", line 61, in remove_client
    client_id = self.client_id
AttributeError: 'NeurositySDK' object has no attribute 'client_id'

Process finished with exit code 1
`

**Comment by thygrrr** [comment]
**Long Term Remedy**

For reference, `signal` code differentiates between these; and none of the Windows signals are handled; and thus the application becomes unstoppable on Windows. Thus, appropriate and portable code should be written. (I'll see if I find the time for a PR if you accept code)

```
    if sys.platform == "win32":
        SIGBREAK: int
        CTRL_C_EVENT: int
        CTRL_BREAK_EVENT: int
    else:
        SIGALRM: int
        SIGBUS: int
        SIGCHLD: int
        SIGCONT: int
        SIGHUP: int
        SIGIO: int
        SIGIOT: int
        SIGKILL: int
        SIGPIPE: int
        SIGPROF: int
        SIGQUIT: int
        SIGSTOP: int
        SIGSYS: int
        SIGTRAP: int
        SIGTSTP: int
        SIGTTIN: int
        SIGTTOU: int
        SIGURG: int
        SIGUSR1: int
        SIGUSR2: int
        SIGVTALRM: int
        SIGWINCH: int
        SIGXCPU: int
        SIGXFSZ: int
        if sys.platform != "darwin":
            SIGCLD: int
            SIGPOLL: int
            SIGPWR: int
            SIGRTMAX: int
            SIGRTMIN: int
```
